### ISSUE TITLE
Post call error

### ISSUE THREAD

**Issue by nalinbuddhika** [kirkone/KK.AspNetCore.EasyAuthAuthentication#50]
Set this up on a .net Core app that hosts an Angular app as the front end. I can make Get calls from SPA without issues, but Post calls fail with "You do not have permission to view this directory or page.". See the following error in the Logs.

2020-07-22T01:41:33
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.PutBlock(String blockId, Stream blockData, String contentMD5, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AddNewBlockToBlob(Stream stream, List`1 blockIds, CloudBlockBlob blockBlob)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
Request Information
RequestID:
RequestDate:Wed, 22 Jul 2020 01:41:33 GMT
StatusMessage:The specified container does not exist.
ErrorCode:ContainerNotFound

**Comment by paule96** [comment]
can you provide sample code? It looks like an error in your routing configuration. We don't test routes with this package. 
Or can you try it first without this package?

**Comment by abeckDev** [comment]
Hi @nalinbuddhika,

and thanks for using KK EasyAuthAuthentication!

After analyzing your Stacktrace, I believe that the error might be in another part of your application. 
May I ask you, if your .Net Core App is establishing a connection to an Azure (Blob) Storage Account?

The inner error is showing that there might be issues with the connection between your .Net App and your Azure Storage Account.
```at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AddNewBlockToBlob``` and 
```
StatusMessage:The specified container does not exist.
ErrorCode:ContainerNotFound
```
are both showing issues with the (Blob) Storage Client. 

Usually the (Authenticated) Controller calls these services in order to interact with other third party services (as Azure Storage Account) and **that's why I believe that the Authentication has already been handled correctly and there is no error in your Auth Framework.**

I think the Issue is not within KK.EasyAuth but with the Storage Account interaction and could be on of the following issues:

**1. The Blob Container does not exist and you don't have permissions to create one**


When working with the Storage Account SDK you need to create a working Authentication against an Azure Endpoint. This is usualy done with a connection string or a SAS token. 

It could be that your connection method might not have the needed rights to create Container on Storage Account level, which could then result in a ```NotAuthorizedException```.

In that case could you either:

- Extend the rights of you SAS Token or double check the connection string
- Validate that you are trying to create a non existing container before trying to append a block to it

**2. You are trying to append a Blob to a Blob Container but never created the container**


When you try to upload a Blob to a BlobContainer which does not exist, you most likely will end in one of these: ```ErrorCode:ContainerNotFound``` Exceptions. 

In that case you just wanna double check, if the container to which your are trying to push is already present. 

You can do this either manual, [as described here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-portal#create-a-container). 

Or by using the SDK like in the sample below:

```C#
private static async Task<CloudBlobContainer> CreateSampleContainerAsync(CloudBlobClient blobClient)
{
    // Name the sample container based on new GUID, to ensure uniqueness.
    // The container name must be lowercase.
    string containerName = "container-" + Guid.NewGuid();

    // Get a reference to a sample container.
    CloudBlobContainer container = blobClient.GetContainerReference(containerName);

    try
    {
        // Create the container if it does not already exist.
        bool result = await container.CreateIfNotExistsAsync();
        if (result == true)
        {
            Console.WriteLine("Created container {0}", container.Name);
        }
    }
    catch (StorageException e)
    {
        Console.WriteLine("HTTP error code {0}: {1}",
                            e.RequestInformation.HttpStatusCode,
                            e.RequestInformation.ErrorCode);
        Console.WriteLine(e.Message);
    }

    return container;
}
```
 Source: [Microsoft Doku](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-container-create#create-a-container)


I hope this helps to clarify things a bit. 
Feel free to reach out if there are any problems.

Regards, 

AbeckDev

**Comment by nalinbuddhika** [comment]
Thank you very much for the reply. I managed to fix the issue.
Issue was in the startup.cs of the app we had following;
**context.Response.Headers.Add("Referrer-Policy", "no-referrer");**
After removing it I am able to make post calls. And the storage error was not related to this.
Thanks again for your support.
